### NUMPY
This is a fundamental Package for scientific computing for manipulation of multi-dimensional arrays and matrices. It is particularly useful for linear algebra, Fourier transform, rand number simulation, etc.

**Matrices** are rectangular array of numbers,symbols and expressions arranged in rows and columns. The numbers, symbols or expressions in the matrix are called its entries or its elements. The horizontal and vertical lines in a matrix are called rows and columns, respectively. It's operations include addition, subtraction and multiplication

The first step is to import numpy library into the active notebook.

In [1]:
import numpy

To shorten the length of any library, a better alternative is to instantiate the library witha shorter name, as in:

In [2]:
import numpy as np

With this, each time numpy is required on this active notebook, `np` will be used instead. 

In [4]:
#creating a 1 dimensional array

x = np.array([1, 2, 3, 4, 5])
y= np.array([9, 10])

print(x)
print('The shape of x is', x.shape)

print(y)
print('The shape of Y is', y.shape)

[1 2 3 4 5]
The shape of x is (5,)
[ 9 10]
The shape of Y is (2,)


In [5]:
#creating a 2D array
z = np.array([[1,2],[3,4]])

print(z)
print('The shape of Y is', z.shape)

[[1 2]
 [3 4]]
The shape of Y is (2, 2)


In [8]:
#creating a multidimensional array

w = np.array([[[1,2,3],[4,5,6], [7,8,9]], [[10, 11, 12], [13,14,15], [16,17,18]], [[19,20,21],[22,23,24], [26,27,28]]])

print(w, '\n')

print('The shape of w is', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]] 

The shape of w is (3, 3, 3)


**Numpy Functions**

Numpy has built-in functions for creating arrays. These include:

* arange
* reshape
* zeros
* ones
* full
* linspace
* random

> The dimensions (no. of rows and columns) are passed s parameters to the function.

In [13]:
#arange is used to create arrays with values in a specified range

A10 = np.arange(10)
A10
print(A10)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#to change a scalar matrix to vector

B10 = A10.reshape(-1,1)

print(A10, '\n', B10)
print('The shape of 1D array X = ', B10.shape)

[0 1 2 3 4 5 6 7 8 9] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
The shape of 1D array X =  (10, 1)


In [19]:
A10 = B10.reshape(2,5)
print(A10)

print('The shape of 1D array X = ', A10.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
The shape of 1D array X =  (2, 5)


> Note: The new dimension must be compatible with the old one.

In [25]:
# zeros is used to create an array filled with zeros.

np_zeros = np.zeros((2,3))

np_zeros #float result

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# specifying the desired data type

np_zeros = np.zeros((2,3))

np_zeros.astype(int) #converting to integer


array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
#ones is used to create an array filled with ones
np_ones = np.ones((2,3))

np_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# full function creates a n*n array filled with a specified given value
np_full = np.full((2,3),4)

np_full

array([[4, 4, 4],
       [4, 4, 4]])

In [30]:
# the eye function lets you create a n*n diagonal (identity) matrix
np_eye = np.eye(6,6)

np_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np_eye = np.eye(3,8)

np_eye.astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]])

In [32]:
#linspace returns evenly spaced numbers over a specified interval
np_linspace = np.linspace(0,10, num=6)

np_linspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
np_linspace = np.linspace(0,10, num=5)

np_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#This creates an array filled with random values between 0 and 1
np_rand = np.random.random_sample((2,3))

np_rand

array([[0.37148322, 0.22032344, 0.68098175],
       [0.39327662, 0.90370926, 0.52471027]])

In [37]:
np_rand1 = np.random.rand(2,3)
np_rand1

array([[0.93416159, 0.89774146, 0.74458141],
       [0.96242609, 0.89407568, 0.68114655]])

In [55]:

x =  np.random.randint(10, size=(3,5))
 
x

array([[2, 8, 0, 7, 0],
       [2, 6, 9, 5, 5],
       [4, 4, 0, 8, 5]])

In [79]:
np_rand = np.random.random_sample((2,3))
np.save('array_data.npy', np_rand)
np_rand #still changing,will find out later

array([[0.01650521, 0.2149057 , 0.97447369],
       [0.97665743, 0.49746181, 0.29095681]])

#### Accessing Elements of Numpy Array
> To access an element in a two-dimensional array, you need to specify an index for both the row and column

In [81]:
z

array([[1, 2],
       [3, 4]])

In [80]:
#row 1, column 0 gives a scalar
z[1,0]

3

In [83]:
#or

p = z[1][0]
p

3

In [84]:
z[1,1]

4

In [86]:
p = (z[0:1,0])
p

array([1])

### Numpy Attributes

Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array. The exposed attributes are the core parts of an array and only some of them can be reset meaningfully without creating a new array

Some commonly used attributes are:

* Shape: indicates the size of an array

* Size: retums the total number of elements in the NumPy array

* Dtype: returns the type of elements in the array, ie, int64, character

In [88]:
print ("The Dtype of elements in array X =", x.dtype)
print ("The shape of ND array w =", w.dtype)

The Dtype of elements in array X = int32
The shape of ND array w = int32


In [90]:
print ("The shape of 10 array X =", x.shape)
print ("The shape of 2D array Z = ", z.shape)
print ("The shape of ND array w =", w.shape)
print ("The shape of arange A10 =", A10.shape)

The shape of 10 array X = (3, 5)
The shape of 2D array Z =  (2, 2)
The shape of ND array w = (3, 3, 3)
The shape of arange A10 = (2, 5)


In [92]:
print ("The shape of ND array W = ", w.size)
print ("The shape of arange A10 = ", A10.size)

The shape of ND array W =  27
The shape of arange A10 =  10


#### Numpy array math operations


In [93]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[2,2,2], [3,3,3]])
z = np.array([1,2,3])

In [94]:
#Transpose a matrix
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
#Elementwise addittion
print (x+y)
print (np.add(x,y))

[[3 4 5]
 [7 8 9]]
[[3 4 5]
 [7 8 9]]


In [97]:
#Elementwise subtraction
print(x-y)
print(np.subtract(x,y))

[[-1  0  1]
 [ 1  2  3]]
[[-1  0  1]
 [ 1  2  3]]


In [100]:
#Elementwise multiplication
print (x*z)
print (np.multiply(x,z))

[[ 1  4  9]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


In [101]:
#Elementwise division
print (x/y)
print (np.divide(x,y))

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]
